from _typeshed import Incomplete
from django.core.urlresolvers import reverse as reverse, reverse_lazy as reverse_lazy

class RemovedInDjango20Warning(DeprecationWarning): ...

class CallableBool:
    do_not_call_in_templates: bool
    value: Incomplete
    def __init__(self, value) -> None: ...
    def __bool__(self) -> bool: ...
    def __call__(self): ...
    def __nonzero__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __or__(self, other): ...
    def __hash__(self): ...

CallableFalse: Incomplete
CallableTrue: Incomplete
