from .compat import CallableFalse as CallableFalse, CallableTrue as CallableTrue
from .settings import api_settings as api_settings
from _typeshed import Incomplete

class TokenUser:
    is_active: bool
    token: Incomplete
    def __init__(self, token) -> None: ...
    def id(self): ...
    def pk(self): ...
    def username(self): ...
    def is_staff(self): ...
    def is_superuser(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...
    def save(self) -> None: ...
    def delete(self) -> None: ...
    def set_password(self, raw_password) -> None: ...
    def check_password(self, raw_password) -> None: ...
    @property
    def groups(self): ...
    @property
    def user_permissions(self): ...
    def get_group_permissions(self, obj: Incomplete | None = ...): ...
    def get_all_permissions(self, obj: Incomplete | None = ...): ...
    def has_perm(self, perm, obj: Incomplete | None = ...): ...
    def has_perms(self, perm_list, obj: Incomplete | None = ...): ...
    def has_module_perms(self, module): ...
    @property
    def is_anonymous(self): ...
    @property
    def is_authenticated(self): ...
    def get_username(self): ...
    def __getattr__(self, attr): ...
